require("user.options")
require("user.plugins")
require("user.colorscheme")
require("user.keymaps")
require("user.cmp")
require("user.crates")
require("user.lsp")
require("user.lualine")
require("user.gitsigns")
require("user.tree-sitter")
require("user.alpha")
require("user.project")
require("user.nvim-tree")
require("user.lsp-signature")
require("user.rust-tools")
require("user.telescope-vimwiki")
require("user.vimwiki")
-- require "user.lspsaga"
--require "ftplugin.rust"
